spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb 
    username: sa
    password: 
    driver-class-name: org.h2.Driver
#url: jdbc:postgresql://localhost:5432/postgres
#username: postgres
#password: demente
#driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: 1987diegog
      password: admin